$fond = FiraCode Nerd Font Mono

general {
  hide_cursor = false
}

animations {
  enabled = false
}

background {
  monitor = eDP-1
  path = ~/pictures/wallpapers/forest-bridge.jpg
  blur_passes = 2
}

input-field {
    monitor = eDP-1
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgb(4f4f4f)
    check_color = rgb(1a5fb4)
    fail_color = rgb(ed333b)

    font_color = rgb(deddda)
    fade_on_empty = false
    rounding = 5

    font_family = $font
    placeholder_text = Say friend and enter
    fail_text = $PAMFAIL

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = $TIME
    font_size = 40
    font_family = $font

    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 20
    font_family = $font

    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = $LAYOUT[en,ru]
    font_size = 13
    onclick = hyprctl switchxkblayout all next

    position = 220, -20
    halign = center
    valign = center
}
