# ----------
# Monitors
# ----------

monitor=eDP-1, 1920x1080@60.05, 0x0, 1

# ----------
# Programs
# ----------

exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprsunset
exec-once = waybar

$terminal = kitty
$fileManager = kitty -e ranger
$browser = firefox
$menu = pgrep wofi > /dev/null 2>&1 && killall wofi || wofi --show drun

# ----------
# Input
# ----------

input {
  kb_layout = us,ru
  kb_options = grp:win_space_toggle

  touchpad {
    natural_scroll = true
  }
}

cursor {
  no_hardware_cursors = true
}

# ----------
# Design
# ----------

animations {
  enabled = false
}

general {
  gaps_in = 5
  gaps_out = 10

  border_size = 1

  resize_on_border = true

  layout = dwindle
}

decoration {
  rounding = 0

  active_opacity = 1.0
  inactive_opacity = 1.0
}

dwindle {
  force_split = 2
  preserve_split = true
}

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
}

# ----------
# Keybinds
# ----------

$mainMod = SUPER

# Programs
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, W, exec, $browser
bind = $mainMod, D, exec, $menu

# Windows
bind = $mainMod, Q, killactive,
bind = $mainMod SHIFT, SPACE, togglefloating
bind = $mainMod, F, fullscreen
bindm = $mainMod, mouse:272, movewindow

# Screen lock
bind = $mainMod, L, exec, hyprlock

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6

bind = $mainMod SHIFT, H, swapwindow, l
bind = $mainMod SHIFT, L, swapwindow, r
bind = $mainMod SHIFT, K, swapwindow, u
bind = $mainMod SHIFT, J, swapwindow, d

# Misc
bind = $mainMod SHIFT, S, exec, hyprshot --mode region --output-folder ~/pictures/screenshots
